### PR TITLE
Add sample param to Standard Deviation and Coefficient of Variation functions

### PR DESCRIPTION
**Pull request by lidimayra**
Boolean param _sample_ in `variance()` makes it possible to choose between Sample or Population. Although `standard_deviation()` and `coefficient_of_variation()` methods calls `standard_deviation()` to calculate the final result, neither of them passed this param. As _sample_ is the default param in `variance()`, there was no way to calculate Standard Deviation or Coefficient of Variation for a population dataset.

Changes made in this pull request adds _sample_ param to both. (with default value set to `True`)

### CODE REVIEW

**Comment by sheriferson** [comment]
This is a great improvement to the functions that rely on `standard_deviation()`. I especially appreciate updating the documentation and tests. Thanks!

Could you extend this improvement to `z_scores()`? Right now `z_scores` calls `standard_deviation` without the ability to specify `sample = False`.

I'm happy to merge the pull request after that extension.

**Comment by lidimayra** [comment]
Sure! I can do it right away!! :blush:

**Comment by sheriferson** [comment]
Awesome! Thanks for the pull request :)

**Comment by lidimayra** [comment]
My pleasure! :)

**Pull request merged**
