### PR TITLE
Coefficient of Variation calculation

### PR DESCRIPTION
**Pull request by lidimayra**
Added a method to calculate the [Coefficient of Variation](https://en.wikipedia.org/wiki/Coefficient_of_variation) of a dataset.

### CODE REVIEW

**Comment by sheriferson** [comment]
Hey thanks for the pull request! This looks great.
Would you mind adding a row to the Measures of Dispersion table in `README.md` with an example of using the function? I'm happy to merge the pull request after that.

**Comment by sheriferson** [comment]
Looks great. Thanks again.

**Comment by lidimayra** [comment]
You're welcome, @sheriferson! :)

There's just one thing: I'm not sure if I [linked the documentation](https://github.com/sheriferson/simplestatistics/pull/7/files#diff-04c6e90faac2675aa89e2176d2eec7d8R118) in the right way. It's the first time I'm doing something using readthedocs.

I generated the documentation on my machine using `make html` and it seemed ok. But I'm not sure if that's enough to generate it online.

If there's anything else to be done, feel free to ask!

**Comment by sheriferson** [comment]
You did everything right! [Read the docs](https://readthedocs.org) watches the repo and automatically (re)generates the documentation when it notices new commits.

You can see that documentation for the coefficient of variation [is already live](http://simplestatistics.readthedocs.io/en/latest/#coefficient-of-variation).

Generating the documentation on your local machine using `make html` lets you view it locally before you push the changes to the remote repo, but it's unrelated to them being generated online.

If you feel like adding any other functions or features the input is always appreciated, and if you want to request the addition of anything, requests are welcome.

**Pull request merged**
